### PR TITLE
Cleanup, fix adding runtime to every file, add `useModule` option

### PR DESCRIPTION
**Pull request by SimonDegraeve**

### CODE REVIEW

**Comment by matAtWork** [comment]
I have a few questions (mainly due to my ignorance of Babel - I might be wrong about all of them):

* Why use babel.transform() for generating an AST from the runtime, since the runtime is ES5 by definition, and is relatively slow compared to acorn (which nodent uses)?
* I think the test for FunctionExpression $wasAsync might be too tight - what about FunctionDeclarations and ArrowFunctionExpressions? Plus, I think such 'detection' should probably be down to some option - maybe I want the runtime alone for bundling, and I don't want to have to define a random async function just to make it show up.
* I think by leaving the location info in the runtime, and not concatenating it down to a single line, source-maps will be wrong (I've not checked, but remember setting it up to work), or is this achieved with the "unshiftContainer" method.

**Comment by SimonDegraeve** [comment]
1) I used `babel.transform()` because it seems cleaner. But I can change it back to acorn if you want.

2) I can change the test to detect any node with the `$wasAsync` property.

> maybe I want the runtime alone for bundling, and I don't want to have to define a random async function just to make it show up.

I think we could always output the runtime if we use the directive.

3) From my tests the sourcemaps works. But I can the fix back.

**Comment by matAtWork** [comment]
Do you have the time to create test cases for (2)? I have to admit that $ properties should have been all cleaned away by nodent before returning the AST, as they are private and could easily confuse babel or something else. 

I think the issue with source maps was quite subtle, something along the lines of the rare cases where nodent generates two outputs from the same input node (stuff like conditionals) Babel throw an exception an exited. In truth I don't use Babel enough to have kept a useful history og what the issue was (or even if it still exists - it could have been fixed)

I'm still tweaking & testing nodent v3. As soon as that's good I'll start testing against fast-async and merge the changes then. I should be done today/tomorrow, unless you find any more bugs :)

**Comment by SimonDegraeve** [comment]
I do not really understand how you make your tests, so I don't think I will dig to much to add it, sorry.
I made the other changes.

**Pull request merged**
